#!/bin/bash


TestName=$1

outfile=$TestName.nc

paramfile=BG_param.txt
echo "#################################" >$paramfile
echo "# Bathymetry file" >>$paramfile
echo "bathy = Bathy_D.asc;" >>$paramfile
echo "posdown=1;" >>$paramfile
echo "yo = -0.024" >>$paramfile
echo "ymax = 3.45" >>$paramfile

echo "# Model controls" >>$paramfile
echo "gpudevice = 0;" >>$paramfile
echo "" >>$paramfile

echo "# Flow parameters" >>$paramfile
echo "eps = 0.00010000;" >>$paramfile
echo "cf=0.001;" >>$paramfile
echo "" >>$paramfile


echo "# Timekeeping parameters" >>$paramfile
echo "CFL = 0.500000;" >>$paramfile
echo "outputtimestep = 1.000000;" >>$paramfile
echo "outvars = zs,hh,uu,vv,zb;" >>$paramfile
echo "endtime = 30.000000;" >>$paramfile
echo "" >>$paramfile

echo "smallnc=0" >>$paramfile
echo "" >>$paramfile

echo "# Files" >>$paramfile
echo "outfile = $outfile;" >>$paramfile
echo "leftbndfile = MonaiValley_InputWave.txt;" >>$paramfile
echo "left = 2" >>$paramfile
echo "right = 0;" >>$paramfile
echo "top = 0;" >>$paramfile
echo "bot = 0;" >>$paramfile
echo "" >>$paramfile

echo "# Time series output" >>$paramfile
echo "TSOfile = gauge1-$TestName.txt" >>$paramfile
echo "TSnode = 4.521, 1.196; #Note these are x, y values converted to the nearest i,j" >>$paramfile
echo "" >>$paramfile

echo "TSOfile = gauge2-$TestName.txt" >>$paramfile
echo "TSnode = 4.521, 1.696;" >>$paramfile
echo "" >>$paramfile

echo "TSOfile = gauge3-$TestName.txt" >>$paramfile
echo "TSnode = 4.521, 2.196;" >>$paramfile
echo "" >>$paramfile


./BasCGPU
CPUruntime=182

runtime=`awk 'END{print($3)}' BG_log.txt`

speedup=`echo "182/$runtime" |bc`


gmt grdmath ${outfile}?zs[29] Benchmark-CPU.nc?zs[29] SUB ABS UPPER = maxerror.nc
merr=`echo "1.0 1.0 " | grdtrack -Gmaxerror.nc -Z`

rm maxerror.nc


printf "%s\t%f\t%f\t%f\n" $TestName $runtime $speedup $merr >>Test_summary.txt


outps=${TestName}_Gauges.ps

region=-R0/25/-0.02/0.05
proj=-JX12c/5c





#Gauge3
gmt psbasemap $region $proj -Bxf2a10+l"time (s)" -Byf0.005a0.01+l"Water level (m)" -BWSen --FONT_ANNOT_PRIMARY=+10p,Helvetica,black -K > $outps
awk '{print($1,$4*0.01)}' ./data/MonaiValley_WaveGages.txt |gmt psxy $region $proj -W1p,black -O -K >> $outps
gmt psxy $region $proj gauge3-BM.txt -W1p,blue -O -K >> $outps
gmt psxy $region $proj gauge3-$TestName.txt -W1p,red -O -K >> $outps

#Legend
echo "Gauge 3" |gmt pstext $region $proj -F+cTL -Dj0.3c -O -K >> $outps


#Gauge2
gmt psbasemap $region $proj -Bxf2a10 -Byf0.005a0.01+l"Water level (m)" -BWSen --FONT_ANNOT_PRIMARY=+10p,Helvetica,black -Y6c -K -O>> $outps
awk '{print($1,$3*0.01)}' ./data/MonaiValley_WaveGages.txt |gmt psxy $region $proj -W1p,black -O -K >> $outps
gmt psxy $region $proj gauge2-BM.txt -W1p,blue -O -K >> $outps
gmt psxy $region $proj gauge2-$TestName.txt -W1p,red -O -K >> $outps

#Legend
echo "Gauge 2" | gmt pstext $region $proj -F+cTL -Dj0.3c -O -K >> $outps

#Gauge1
gmt psbasemap $region $proj -Bxf2a10 -Byf0.005a0.01+l"Water level (m)" -BWSen --FONT_ANNOT_PRIMARY=+10p,Helvetica,black -Y6c -K -O>> $outps
awk '{print($1,$2*0.01)}' ./data/MonaiValley_WaveGages.txt | gmt psxy $region $proj -W1p,black -O -K >> $outps
gmt psxy $region $proj gauge1-BM.txt -W1p,blue -O -K >> $outps
gmt psxy $region $proj gauge1-$TestName.txt -W1p,red -O -K >> $outps
#psxy $region $proj ./out/gauge1_AG.txt -W1p,blue -O -K >> $outps
#psxy $region $proj ./out/gauge1_GN.txt -W1p,green -O -K >> $outps
#Legend
echo "Gauge 1" | gmt pstext $region $proj -F+cTL -Dj0.3c -O -K >> $outps
echo "Measured" | gmt pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-0.9c -O -K >> $outps
echo -e "0.5 0.035\n1.5 0.035\n" | gmt psxy $region $proj -W1p,black -O -K >> $outps
echo "GPU" | gmt pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-1.4c -O -K >> $outps
echo -e "0.5 0.028\n1.5 0.028\n" | gmt psxy $region $proj -W1p,red -O -K >> $outps
echo "CPU" | gmt pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-2.1c -O -K >> $outps
echo -e "0.5 0.021\n1.5 0.021\n" | gmt psxy $region $proj -W1p,blue -O -K >> $outps
#echo "Adaptive" | pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-1.9c -O -K >> $outps
#echo -e "0.5 0.021\n1.5 0.021\n" | psxy $region $proj -W1p,blue -O -K >> $outps
#echo "Adaptive, Green-Naghdi" | pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-2.4c -O -K >> $outps
#echo -e "0.5 0.014\n1.5 0.014\n" | psxy $region $proj -W1p,green -O -K >> $outps

gmt psxy -R -J -O -T >> $outps
gmt psconvert -A -P -Tg $outps
