#!/bin/bash

datafile=$1

outps=BM_Results_Gauges.ps

region=-R0/25/-0.02/0.05
proj=-JX12c/5c

#Gauge3
psbasemap $region $proj -Bxf2a10+l"time (s)" -Byf0.005a0.01+l"Water level (m)" -BWSen --FONT_ANNOT_PRIMARY=+10p,Helvetica,black -K > $outps
awk '{print($1,$4*0.01)}' ../Data/MonaiValley_WaveGages.txt | psxy $region $proj -W1p,black -O -K >> $outps
psxy $region $proj gauge3-BM.txt -W1p,red -O -K >> $outps

#Legend
echo "Gauge 3" | pstext $region $proj -F+cTL -Dj0.3c -O -K >> $outps


#Gauge2
psbasemap $region $proj -Bxf2a10 -Byf0.005a0.01+l"Water level (m)" -BWSen --FONT_ANNOT_PRIMARY=+10p,Helvetica,black -Y6c -K -O>> $outps
awk '{print($1,$3*0.01)}' ../Data/MonaiValley_WaveGages.txt | psxy $region $proj -W1p,black -O -K >> $outps
psxy $region $proj gauge2-BM.txt -W1p,red -O -K >> $outps

#Legend
echo "Gauge 2" | pstext $region $proj -F+cTL -Dj0.3c -O -K >> $outps

#Gauge1
psbasemap $region $proj -Bxf2a10 -Byf0.005a0.01+l"Water level (m)" -BWSen --FONT_ANNOT_PRIMARY=+10p,Helvetica,black -Y6c -K -O>> $outps
awk '{print($1,$2*0.01)}' ../Data/MonaiValley_WaveGages.txt | psxy $region $proj -W1p,black -O -K >> $outps
psxy $region $proj gauge1-BM.txt -W1p,red -O -K >> $outps
#psxy $region $proj ./out/gauge1_AG.txt -W1p,blue -O -K >> $outps
#psxy $region $proj ./out/gauge1_GN.txt -W1p,green -O -K >> $outps
#Legend
echo "Gauge 1" | pstext $region $proj -F+cTL -Dj0.3c -O -K >> $outps
echo "Measured" | pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-0.9c -O -K >> $outps
echo -e "0.5 0.035\n1.5 0.035\n" | psxy $region $proj -W1p,black -O -K >> $outps
echo "CPU" | pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-1.4c -O -K >> $outps
echo -e "0.5 0.028\n1.5 0.028\n" | psxy $region $proj -W1p,red -O -K >> $outps
#echo "Adaptive" | pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-1.9c -O -K >> $outps
#echo -e "0.5 0.021\n1.5 0.021\n" | psxy $region $proj -W1p,blue -O -K >> $outps
#echo "Adaptive, Green-Naghdi" | pstext $region $proj -F+f10p,Helvetica,black+cTL -D1.0c/-2.4c -O -K >> $outps
#echo -e "0.5 0.014\n1.5 0.014\n" | psxy $region $proj -W1p,green -O -K >> $outps

psxy -R -J -O -T >> $outps
psconvert -A -P -Tg $outps



#file2plot=filename5876.txt


# Map eta
#res=`echo "5.448/(2^9-1)" |bc -l`
#echo $res
#region=-R0/5.448/0/3.402
#proj=-JX15c/0
#outps=test100.ps


#awk '{if(NR>1 && $1!=""){print($1,$2,$3)}}' $file2plot | xyz2grd $region -I$res -Gzs.nc
#awk '{if(NR>1 && $1!=""){print($1,$2,$4)}}' $file2plot | xyz2grd $region -I$res -Gh.nc

#grdmath h.nc 0.0001 GT 0 NAN = nanland.nc

#grdmath nanland.nc zs.nc MUL = toplot.nc


#makecpt -T-0.02/0.04/0.0001 -Cjet >WLev.cpt
#psbasemap $region $proj -Bxa0.5f0.1+l"m" -Gwheat -Bya0.5f0.1+lm -BWSen -K > $outps
#grdimage $region $proj toplot.nc -CWLev.cpt -Q -O -K>> $outps
#psxy -R -J -O -T >> $outps
#psconvert -A -P -Tg $outps


# Map Level
#outps=test_Lev100.ps


#awk '{if(NR>1 && $1!=""){printf("%f\t%f\t%d\n",$1,$2,$5)}}' $file2plot | xyz2grd $region -I$res -Gtest.nc
#makecpt -T0/9/1 -Cjet >Level.cpt
#psbasemap $region $proj -Bxa0.5f0.1+l"m" -Bya0.5f0.1+lm -BWSen -K > $outps
#grdimage $region $proj test.nc -CLevel.cpt -O -K>> $outps
#psxy -R -J -O -T >> $outps
#psconvert -A -P -Tg $outps
